services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports: 
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
  
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      device: /home/mottjes/data/wordpress
      type: none
      o: bind
    
  mariadb_data:
    driver: local
    driver_opts:
      device: /home/mottjes/data/mariadb
      type: none
      o: bind